# SPDX-License-Identifier: GPL-2.0
icc-bcm-voter-objs			:= bcm-voter.o
icc-smd-rpm-objs			:= smd-rpm.o icc-rpm.o
icc-rpmh-obj				:= icc-rpmh.o
qnoc-sdm660-objs			:= sdm660.o

obj-$(CONFIG_INTERCONNECT_QCOM_BCM_VOTER) += icc-bcm-voter.o
obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += icc-smd-rpm.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM660) += qnoc-sdm660.o
